// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using entityFramework;

#nullable disable

namespace entityFramework.Migrations
{
    [DbContext(typeof(TareasContext))]
    [Migration("20230402221357_InitialData")]
    partial class InitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("entityFramework.Models.Categoria", b =>
                {
                    b.Property<Guid>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Peso")
                        .HasColumnType("int");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categoria", (string)null);

                    b.HasData(
                        new
                        {
                            CategoriaId = new Guid("4ed10ffb-a8cf-4360-953f-1173f0a1c2e0"),
                            Descripcion = "Descripción de la categoría 1",
                            Nombre = "Actividades pendientes",
                            Peso = 20
                        },
                        new
                        {
                            CategoriaId = new Guid("4ed10ffb-a8cf-4360-953f-1173f0a1c202"),
                            Descripcion = "Descripción de la categoría 1",
                            Nombre = "Actividades personales",
                            Peso = 50
                        });
                });

            modelBuilder.Entity("entityFramework.Models.Tarea", b =>
                {
                    b.Property<Guid>("TareaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("PrioridadTarea")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TareaId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Tarea", (string)null);

                    b.HasData(
                        new
                        {
                            TareaId = new Guid("4ed10ffb-a8cf-4360-953f-1173f0a1c210"),
                            CategoriaId = new Guid("4ed10ffb-a8cf-4360-953f-1173f0a1c2e0"),
                            FechaCreacion = new DateTime(2023, 4, 2, 18, 13, 57, 499, DateTimeKind.Local).AddTicks(1090),
                            PrioridadTarea = 1,
                            Titulo = "Revisar pago de servicios publicos"
                        },
                        new
                        {
                            TareaId = new Guid("4ed10ffb-a8cf-4360-953f-1173f0a1c211"),
                            CategoriaId = new Guid("4ed10ffb-a8cf-4360-953f-1173f0a1c202"),
                            FechaCreacion = new DateTime(2023, 4, 2, 18, 13, 57, 499, DateTimeKind.Local).AddTicks(1155),
                            PrioridadTarea = 0,
                            Titulo = "Terminar de ver peliculas de Marvel"
                        });
                });

            modelBuilder.Entity("entityFramework.Models.Tarea", b =>
                {
                    b.HasOne("entityFramework.Models.Categoria", "Categoria")
                        .WithMany("Tareas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("entityFramework.Models.Categoria", b =>
                {
                    b.Navigation("Tareas");
                });
#pragma warning restore 612, 618
        }
    }
}
